let a = 100;
let b ="programing";
let c = true;
let d =false;
let e =3.1416;
console.log("a:",typeof a);
console.log("b:",typeof b);
console.log("c:",typeof c);
console.log("d:",typeof d);
console.log("e:",typeof e);
